server:
    port: 9082
spring: 
    application:
        name: tcc-product-service
    datasource: 
        url: jdbc:mysql://localhost:3306/tcc_product?&useSSL=false&characterEncoding=UTF-8
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
jfish: 
    mq:
        transactional:
            enabled: true
            sendTask:
                enabled: true
    ons:
        serverType: rocketmq
        onsAddr: localhost:10911
        #serializer: TYPING_JSON
        namesrvAddr: localhost:9876